### ISSUE TITLE
Assert strand == '+' or strand == '-' 

### ISSUE THREAD

**Issue by andredsim** [LRGASP/lrgasp-challenge-1-evaluation#1]
![image](https://user-images.githubusercontent.com/17838991/126740330-e90d2f68-d87a-412b-bf37-35751e0dabb9.png)

Hi LRGASP team,

I tried running the challenge 1 evaluation code using the GTF output from Stringtie2 but get an Assertion error (see picture for command line and error message). The GTF file did have lines where the stand was annotated as '.' however when I replaced these with '+' and confirmed that all lines were either a '+' or '-' I continued to get the same error. Is there a work around to this or perhaps something obvious I might be doing wrong?

**Comment by FJPardoPalacios** [comment]
Hi @andredsim ,

Is it possible that between the failed run and the one with all the strands being "+" or "-" you didn't remove previous intermediary files? 
I think that is what's happening: intermediary files still contain the "." information for some transcripts and as they are re-used, the error occurs. Try to remove any previous output files and re-run it.

Bests,
Fran

**Comment by andredsim** [comment]
Hi @FJPardoPalacios 
Yes that appears to be the case and it has run through now. Thanks for the guidance!
Are there plans to have this pipeline ignore non '+' and '-' lines in future or should I continue to remove these lines from my output gtfs in future to prevent this error returning?
