### ISSUE TITLE
problem when building cDNA_Cupcake

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-challenge-1-evaluation#2]
Hello,
I installed thesqanti3_lrgasp conda env, activated it, cloned the cDNA_Cupcake repo, then:
`(sqanti3_lrgasp) $ python setup.py build`
`Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
`

it looks like I'm missing Cython on my system. Wouldn't it make sense to include it in sqanti3_lrgasp.yml?
Thanks!

**Comment by julienlag** [comment]
solved by running
`conda install -c anaconda cython`
from within the `sqanti3_lrgasp` conda env before `python setup.py build`
@FJPardoPalacios could you please add cython to the yml file? Or alternatively add the above command to the installation instructions, thanks!

**Comment by FJPardoPalacios** [comment]
Sorry, I missed this issue. 
I've already added cython to `sqanti3_lrgasp.yml` and the problem should be fixed.

Thanks!
