### ISSUE TITLE
links to data files

### ISSUE THREAD

**Issue by julienlag** [LRGASP/lrgasp-challenge-1-evaluation#3]
Hello,
I don't know if it's a deliberate choice, but file links in the README.md file point to the github HTML page instead of the raw file, e.g.:

https://github.com/LRGASP/lrgasp-challenge-1-evaluation/blob/main/sqanti3_lrgasp.yml

instead of 

https://raw.githubusercontent.com/LRGASP/lrgasp-challenge-1-evaluation/main/sqanti3_lrgasp.yml

 IMHO this is very impractical and borderline dangerous. Impractical because upon clicking, you first land on the github HTML page, then have to click on "Raw" to get the actual file. Dangerous because if you instead "right-click" -> "copy link URL", then input this URL to wget, you will download a file named sqanti3_lrgasp.yml but the contents will actually be HTML (same goes for BED files etc.)

**Comment by FJPardoPalacios** [comment]
Thank you for the suggestion! I just fixed those links.
